version: '3'
services:
  nginx-proxy:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "81:81"    # Admin UI
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruizdev7-app
    restart: unless-stopped
    expose:
      - "3000" # Puerto interno de la aplicación
    networks:
      - app-network

networks:
  app-network:
    driver: bridge