version: '3'
services:
  astro-app:
    build: .
    restart: unless-stopped
    networks:
      - npm-network

  nginx-proxy:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "81:81"    # Admin UI
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - npm-network

networks:
  npm-network:
    driver: bridge